/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/quienes-somos': typeof QuienesSomosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/quienes-somos': typeof QuienesSomosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/quienes-somos': typeof QuienesSomosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/areas' | '/quienes-somos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/areas' | '/quienes-somos'
  id: '__root__' | '/' | '/areas' | '/quienes-somos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasRoute: typeof AreasRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasRoute: AreasRoute,
  QuienesSomosRoute: QuienesSomosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
